package: add @typescript-eslint/parser
add to dev dependencies @typescript-eslint/parser package.
This fixes the following error during install:

[!] (plugin eslint) Error: Failed to load parser
'@typescript-eslint/parser' declared in '.eslintrc.json':
Cannot find module '@typescript-eslint/parser'
Require stack:
- /home/web/mathlive/.eslintrc.json